# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

jei_version=15.20.0.129
ponder_version=1.0.92
mekanism_version=1.20.1-10.4.16.80
flywheel_version=1.0.6-278
flywheel_version_range =[1.0.0,2.0)


## Mod Properties
mod_id=mekanism_ponders
mod_name=Mekanism: Ponders
mod_license=LGPL-v3.0
mod_version=1.0.0-1.20.1
mod_group_id=io.github.alyx.mekponder
mod_authors=alyx
mod_description=Adds Ponders to various Mekanism features!