modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/a1qs/mekanism_ponders/issues"

#clientSideOnly=true #optional - defaults to false if absent

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://github.com/a1qs/mekanism_ponders" #optional
logoFile="mekanism_ponders.png" #optional
credits="Creators of Create for creating the Ponder System and the developers of Mekanism" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''


[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true #mandatory
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]] #optional
    modId="mekanism" #mandatory
    mandatory=true #mandatory
    versionRange="[10.4.16,)" #mandatory
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]] #optional
    modId="mekanismgenerators" #mandatory
    mandatory=false #mandatory
    versionRange="[10.4.16,)" #mandatory
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId = "flywheel"
    mandatory=true #mandatory
    versionRange = "${flywheel_version_range}"
    ordering = "AFTER"
    side = "CLIENT"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
